apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-trino-gateway.fullname" . }}
  labels:
    {{- include "postgresql-trino-gateway.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "postgresql-trino-gateway.selectorLabels" . | nindent 4 }}
