---
name: Daily Security Audit

on:
  schedule:
    # Run every day at 04:15 UTC: https://crontab.guru/#15_4_*_*_*
    - cron: '15 4 * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998 # v2.0.0
        # Build against stable because cargo-audit sometimes depends on things
        # that require a newer Rust version than our pinned toolchain. This does
        # not influence the result, so it should be safe.
        env:
          RUSTUP_TOOLCHAIN: stable
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
